[package]
name = "retrieval"
version = "0.1.0"
edition = "2021"

[dependencies]
tch = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
